In [1]:
import pandas as pd
Age_series = pd.Series([34,24,56,78,34,45,'a'])
Age_series

0    34
1    24
2    56
3    78
4    34
5    45
6     a
dtype: object

In [2]:
## objects created
dir()

['Age_series',
 'In',
 'Out',
 '_',
 '_1',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'get_ipython',
 'pd',
 'quit']

In [3]:
# delete an object
B =1
del(Age_series,B)

In [4]:
# Age_series

NameError: name 'Age_series' is not defined

In [1]:
########### Appending/ Concatenating data
# for set
Auto_survey1= set(['BMW', 'BMW','AUDI','Merc', 'Merc','Bentley','Mini Cooper','Suzuki','Hundai'])
Auto_survey2= set(['BMW', 'Renault'])
Combined = Auto_survey1 | Auto_survey2
Combined

{'AUDI',
 'BMW',
 'Bentley',
 'Hundai',
 'Merc',
 'Mini Cooper',
 'Renault',
 'Suzuki'}

In [6]:
Intersection_cars = Auto_survey1 & Auto_survey2
print(Intersection_cars)


{'BMW'}


In [8]:
#  Appending lists
list1= [6,3,4,5,2]
list2= [100,101,107,108,107,100]
list1 + list2

[6, 3, 4, 5, 2, 100, 101, 107, 108, 107, 100]

In [9]:
# for list and tuple
tuple1= (6,3,4,5,2)
list2= [100,101,107,108,107,100]
list(tuple1) + list2


[6, 3, 4, 5, 2, 100, 101, 107, 108, 107, 100]

In [10]:
# for tuples
tuple1= (6,3,4,5,2)
tuple2= (100,101,107,108,107,100)
tuple1 + tuple2

(6, 3, 4, 5, 2, 100, 101, 107, 108, 107, 100)

In [11]:
# update a list
First_list = ['Mark',34,19.6,False]
First_list.append("Jonathan")
print(First_list)

['Mark', 34, 19.6, False, 'Jonathan']


In [12]:
## append at defined position
First_list = ['Mark',34,19.6,False]
print(First_list)

First_list.insert(1,"Anderson Thompson")
print(First_list)

['Mark', 34, 19.6, False]
['Mark', 'Anderson Thompson', 34, 19.6, False]


In [13]:
## deleting a record
First_list = ['Mark',34,19.6,False]
First_list.remove('Mark')
First_list.remove(34)
print(First_list)

[19.6, False]


In [16]:
## deleting a record at a defined index value
First_list = ['Mark',34,19.6,False]
print(First_list)
First_list.pop(0)
print(First_list)

['Mark', 34, 19.6, False]
[34, 19.6, False]


In [17]:
## repetition
First_list = ['Mark',34,19.6,False]
First_list*2


['Mark', 34, 19.6, False, 'Mark', 34, 19.6, False]

In [18]:
############### Operators in Python
Student_list = ['Tom','Jack','Nick','Mark','Barb']
print('Nick' in Student_list)
print('Paul' in Student_list)
print('Paul' not in Student_list)


True
False
True


In [22]:
## + operator for concatenation
FN = "Geroge"
LN = "Washington"
print('Customer Name is:',FN+LN)
print('Customer Name is:',FN+" "+LN)

Customer Name is: GerogeWashington
Customer Name is: Geroge Washington


In [23]:
# Comparison operator
Cust_income = 2000
Credit_cards = 2
print(Cust_income >= 1000)
print(Credit_cards>4)
print(Credit_cards != 2) # not equal to
print(Credit_cards == 2) # If 2 values are equal or not

True
False
False
True


In [25]:
# Logical operator
## & (and operator) and | (or operator)

print((2>1) & (3>0)) #print((2>1) & (3>0)) # both conditions are true
print((2>1) & (3>100)) #1st is true and 2nd is false
print((2>10) & (3>1)) #1st is false and 2nd is true
print((2>15) & (3>10)) #both are false

True
False
False
False


In [26]:
print((2>1) | (3>0)) #print((2>1) & (3>0)) # both conditions are true
print((2>1) | (3>100)) #1st is true and 2nd is false
print((2>10) | (3>1)) #1st is false and 2nd is true
print((2>15) | (3>10)) #both are false

True
True
True
False


In [2]:
# scenario 1
Cust_income = 2000
Credit_cards = 2
### customer should not have more than 3 cards. Income >1800 per month
l = (Cust_income>1800) & (Credit_cards<=3)
print(l)

True


In [28]:
# scenario 2
Cust_income = 1500
Credit_cards = 1
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income >1800) &  (Credit_cards<=3)

False

In [29]:
# scenario 3
Cust_income = 2000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income >1800) &  (Credit_cards<=3)

False

In [31]:
# scenario 4
Cust_income = 1000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income >1800) & (Credit_cards<=3)

False

In [35]:
## or condition with variables - either of condition to be true
# scenario 1
Cust_income = 2000
Credit_cards = 2
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)

True

In [36]:
# scenario 2
Cust_income = 1500
Credit_cards = 1
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)


True

In [37]:
# scenario 3
Cust_income = 2000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)



True

In [38]:
# scenario 4
Cust_income = 1000
Credit_cards = 5
### customer should not have more than 3 cards. Income >1800 per month
(Cust_income>1800) | (Credit_cards<=3)

False

In [43]:
Marks_math = [45,89,56,34,98]
Marks_math
print(sum(Marks_math))
print(min(Marks_math))
print(max(Marks_math))

322
34
98


In [46]:
import statistics
statistics.mean(Marks_math)


64.4

In [47]:
import statistics as st
st.mean(Marks_math)

64.4

In [45]:
dir(statistics)

['Decimal',
 'Fraction',
 'StatisticsError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_counts',
 '_exact_ratio',
 '_fail_neg',
 '_find_lteq',
 '_find_rteq',
 '_isfinite',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'collections',
 'groupby',
 'harmonic_mean',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'numbers',
 'pstdev',
 'pvariance',
 'stdev',
 'variance']

In [50]:
help(st.mode)

Help on function mode in module statistics:

mode(data)
    Return the most common data point from discrete or nominal data.
    
    ``mode`` assumes discrete data, and returns a single value. This is the
    standard treatment of the mode as commonly taught in schools:
    
    >>> mode([1, 1, 2, 3, 3, 3, 3, 4])
    3
    
    This also works with nominal (non-numeric) data:
    
    >>> mode(["red", "blue", "blue", "red", "green", "red", "red"])
    'red'
    
    If there is not exactly one most common value, ``mode`` will raise
    StatisticsError.



In [51]:
Marks_math = [45,89,56,34,98]
len(Marks_math)

5

In [53]:
## numeric functions
Net_operating_income = -2000
abs(Net_operating_income)


2000

In [54]:
import pandas as pd
Nums = pd.Series([-5,-9,5,7])
print(abs(Nums))

0    5
1    9
2    5
3    7
dtype: int64


In [55]:
print(min(Nums))
print(max(Nums))


-9
7


In [58]:
##################### use numpy functions for missing values
Nums = pd.Series([-5,-9,5,7,None,9,10,5,2,9])
sum(Nums)

nan

In [59]:
import numpy as np
np.nansum(Nums)

33.0

In [60]:
import statistics as st
st.mean(Nums)

nan

In [65]:
Nums = pd.Series([-5,-9,5,7,np.NaN,None,9,10,5,2,9])
np.nanmean(Nums)

3.6666666666666665

In [ ]:
Name="John Anderson"
print(Name.upper())
print(Name.lower())


In [66]:
## character functions
Cust_names = pd.Series(["John Smith","Lisa Anderson","thomas brooke","Paul Lodwidge"])
print(Cust_names)
print(type(Cust_names))
print(Cust_names.dtype)


0       John Smith
1    Lisa Anderson
2    thomas brooke
3    Paul Lodwidge
dtype: object
<class 'pandas.core.series.Series'>
object


In [69]:
Cust_names.str.upper()

0       JOHN SMITH
1    LISA ANDERSON
2    THOMAS BROOKE
3    PAUL LODWIDGE
dtype: object

In [70]:
Cust_names.str.lower()

0       john smith
1    lisa anderson
2    thomas brooke
3    paul lodwidge
dtype: object

In [72]:
########### if else condition
Age = 38
if Age<18:
    print('Minor')
else:
    print('Major')

Major


In [73]:
########### if else condition
Age = 10
if Age<18:
    print('Minor')
else:
    print('Major')

Minor


In [74]:
Age = 90
if Age<18:
    print('Minor')
elif Age<50:
    print('Major')
else:
    print('Old')


Old


In [75]:
Age = 45
if Age<18:
    print('Minor')
elif Age<50:
    print('Major')
else:
    print('Old')


Major


In [76]:
Age = 10
if Age<18:
    print('Minor')
elif Age<50:
    print('Major')
else:
    print('Old')

Minor


In [80]:
# nested condition
Age = 16
IQ = "Intelligent"
if Age<18:
    if IQ == "Intelligent":
        print('Minor+Intelligent')
    else:
        print('Minor+Normal')
elif Age<50:
    print('Major')
else:
    print('Old')

Minor+Intelligent


In [82]:
# User defined functions
# step 1 - creating a function
def Print_month():
    return "The current month is March"

# Step 2 - Executing function
Print_month()

'The current month is March'

In [83]:
## function with 1 parameter
# step 1 - creating a function
def Print_month(ThisMonth):
    return "The current month is:" + ThisMonth

# Step 2 - Executing function
Print_month('Jan')

'The current month is:Jan'

In [84]:
## function with > 1 parameter
# step 1 - creating a function
def Print_month(ThisMonth,ThisYear):
    return "The current month is:" + ThisMonth + " and Year is: " + ThisYear

# Step 2 - Executing function
Print_month('March','2020')

'The current month is:March and Year is: 2020'

In [85]:
# Mathematical function
def Power_fn(x,y):
    return x**y

Power_fn(2,3)

8

In [87]:

def check_age(Age):
    if Age<18:
        return 'Minor'
    elif Age<50:
        return 'Major'
    else:
        return 'Old'

check_age(17)

'Minor'

In [90]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [92]:
for i in range(10):
    print(i*5)

0
5
10
15
20
25
30
35
40
45


In [99]:
list_empty=[]
for i in range(10):
    list_empty.append(i*5)
list_empty

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

In [3]:
list1 = [45,34,23]
for i in list1:
    print(i)

45
34
23


In [95]:
list1 = ["Robeta",'Alexa','Barb','Simon']
for i in list1:
    print(i)

Robeta
Alexa
Barb
Simon


In [ ]:
# Below while loop will run for ever
'''
temp = 90
while temp<95:
    temp=temp-1
    print(temp)
'''

In [107]:
Marks_maths = [56,67,78,45]
sorted(Marks_maths)

[45, 56, 67, 78]

In [108]:
sorted(Marks_maths,reverse=True)

[78, 67, 56, 45]

In [109]:
Marks_maths = [56,67,78,45]
for x,y in enumerate(Marks_maths):
    print(x,y)

0 56
1 67
2 78
3 45


In [ ]:
### Lesson 05

In [4]:
import numpy as np
distance = [10,15,23,14]
time = [.3,.47,.2,.1]

In [5]:
# distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [7]:
distance_array = np.array(distance)
distance_array

array([10, 15, 23, 14])

In [8]:
time_array = np.array(time)
time_array

array([0.3 , 0.47, 0.2 , 0.1 ])

In [9]:
distance_array/time_array

array([ 33.33333333,  31.91489362, 115.        , 140.        ])

In [20]:
Marks_maths =   [34,45,89]
Marks_science = [48,55,98]
Marks_socst =   [67,36,60]
Marks_maths + Marks_science + Marks_socst


[34, 45, 89, 48, 55, 98, 67, 36, 60]

In [21]:
np.array(Marks_maths) + np.array(Marks_science) + np.array(Marks_socst)

array([149, 136, 247])

In [5]:
import numpy as np
Marks_maths =   [34,45,89]
Marks_science = [48,55,98]
Marks_socst =   [67,36,60]
l = np.array(Marks_maths)/3 + np.array(Marks_science)/3 + np.array(Marks_socst)/3
print(l)

[49.66666667 45.33333333 82.33333333]


In [17]:
maths_marks =np.array([34,45,89])
maths_marks.dtype

dtype('int64')

In [15]:
maths_marks+5

array([39, 50, 94])

In [22]:
maths_marks.ndim

1

In [24]:
Cust_details=np.array([[34,1000],[35,5000],[45,7000]])
Cust_details

array([[  34, 1000],
       [  35, 5000],
       [  45, 7000]])

In [27]:
Cust_details_Jio_JioFiber = np.array([[[34,1000],[35,5000],[45,7000]],[[36,1800],[65,4000],[49,7600]]])
Cust_details_Jio_JioFiber

array([[[  34, 1000],
        [  35, 5000],
        [  45, 7000]],

       [[  36, 1800],
        [  65, 4000],
        [  49, 7600]]])

In [ ]:
'''
Activity 
*********
Math_marks = xxx
Science_Marks = xxx
1. For a student to get admitted to "Science" Stream he should get Marks in Math >70 AND marks in science as >75 
Other wise he will be into "Non-Science" stream.
2. Exception - If marks in math or science i.e. either is >90 irrespective of fact the point 1 cut off is met or not student will be 
eligible for Science steam.
Create if else condition WITH USER DEFINED FUNCTION with output as "Science stream Eligible" and "Science stream NOT Eligible"
'''

In [18]:
Math_marks = 34
Science_Marks = 20

def Eligible_criteria_fn(Math_marks,Science_Marks):
    if (Math_marks > 70) | (Science_Marks > 75) | (Math_marks > 90) | (Science_Marks > 90):
        return ("Science stream Eligible")
    else:
        return ("Science stream NOT Eligible")
    
Eligible_criteria_fn(Math_marks,Science_Marks)

'Science stream NOT Eligible'

In [12]:
def Eligible_criteria_fn(Math_marks,Science_Marks):
    if Math_marks>70:
        if Science_Marks>75:
            return ("Science stream Eligible")
        else:
            return ("Science stream NOT Eligible")
    else:
            return ("Science stream NOT Eligible")

Eligible_criteria_fn(74,81)

'Science stream Eligible'