In [2]:
#### Lesson 05 - Numpy

10

In [ ]:
len(range(10))

In [6]:
import numpy as np
EmpRecs = np.array([[101,1000],[102,1100],[103,3000]])
EmpRecs

array([[ 101, 1000],
       [ 102, 1100],
       [ 103, 3000]])

In [7]:
EmpRecs.ndim

2

In [9]:
EmpRecs.shape

(3L, 2L)

In [10]:
EmpRecs.size

6

In [11]:
EmpRecs.dtype

dtype('int32')

In [12]:
first_trial_cyclist = np.array([10,56,23,15,34])
second_trial_cyclist = np.array([67,34,21,19,14])
FinalTable = np.array([first_trial_cyclist,second_trial_cyclist])
FinalTable

array([[10, 56, 23, 15, 34],
       [67, 34, 21, 19, 14]])

In [14]:
FinalTable[0]
#or
FinalTable[0,:]

array([10, 56, 23, 15, 34])

In [15]:
FinalTable[0,2]

23

In [16]:
FinalTable[:,1]

array([56, 34])

In [18]:
FinalTable[0,[2,3]]

array([23, 15])

In [19]:
FinalTable[0,[2,4]]

array([23, 34])

In [4]:
a = np.array([1000,567])
b = np.array([True,False])
a[b]
# now refer to slide 33 of Lesson 05

array([1000])

In [5]:
np.pi

3.141592653589793

In [6]:
np.floor(3.676)

3.0

In [7]:
np.ceil(3.676)

4.0

In [9]:
np.exp(1)

2.718281828459045

In [10]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print(new_cyclist_trials)


[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]


In [11]:
print(new_cyclist_trials.ravel())

[10 15 17 26 13 19 12 11 21 24 14 23]


In [14]:
print(new_cyclist_trials.reshape(3,4)) # will not overwrite original data

[[10 15 17 26]
 [13 19 12 11]
 [21 24 14 23]]


In [15]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [17]:
new_cyclist_trials.resize(3,4) # will change original data

In [18]:
new_cyclist_trials

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [20]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [21]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]), array([[26, 13, 19],
        [24, 14, 23]])]

In [22]:
np.vsplit(new_cyclist_trials,2)

[array([[10, 15, 17, 26, 13, 19]]), array([[12, 11, 21, 24, 14, 23]])]

In [24]:
new_cyclist_trials1 = np.array([10,15,17,26,13,19])
new_cyclist_trials2 = np.array([12,11,21,24,14,23])
np.hstack((new_cyclist_trials1,new_cyclist_trials2))


array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [25]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print(new_cyclist_trials)
new_cyclist_trials.transpose()


[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]


array([[10, 12],
       [15, 11],
       [17, 21],
       [26, 24],
       [13, 14],
       [19, 23]])

In [27]:
inverse_array = np.array([[10,20],[15,25]])
print(inverse_array)
np.linalg.inv(inverse_array)

[[10 20]
 [15 25]]


array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [ ]:
# slide 47 as an activity from Lesson 05

In [3]:
countries = np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'])
gdp = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])


In [8]:
#highest GDP
Highest_gdp_country = gdp.argmax()
print(Highest_gdp_country)
countries[Highest_gdp_country]

45


'Norway'

In [9]:
#lowest GDP
Highest_gdp_country = gdp.argmin()
print(Highest_gdp_country)
countries[Highest_gdp_country]

21


'Ethiopia'

In [10]:
# text and input values iteratively
for country_name,gdp_country in zip(countries,gdp):
    print(country_name,gdp_country)

('Algeria', 2255.225482)
('Angola', 629.9553062)
('Argentina', 11601.63022)
('Australia', 25306.82494)
('Austria', 27266.40335)
('Bahamas', 19466.99052)
('Bangladesh', 588.3691778)
('Belarus', 2890.345675)
('Belgium', 24733.62696)
('Bhutan', 1445.760002)
('Brazil', 4803.398244)
('Bulgaria', 2618.876037)
('Cambodia', 590.4521124)
('Cameroon', 665.7982328)
('Chile', 7122.938458)
('China', 2639.54156)
('Colombia', 3362.4656)
('Cyprus', 15378.16704)
('Denmark', 30860.12808)
('El Salvador', 2579.115607)
('Estonia', 6525.541272)
('Ethiopia', 229.6769525)
('Fiji', 2242.689259)
('Finland', 27570.4852)
('France', 23016.84778)
('Georgia', 1334.646773)
('Ghana', 402.6953275)
('Grenada', 6047.200797)
('Guinea', 394.1156638)
('Haiti', 385.5793827)
('Honduras', 1414.072488)
('Hungary', 5745.981529)
('India', 837.7464011)
('Indonesia', 1206.991065)
('Ireland', 27715.52837)
('Italy', 18937.24998)
('Japan', 39578.07441)
('Kenya', 478.2194906)
('South Korea', 16684.21278)
('Liberia', 279.2204061)
('Mala

In [13]:
# last question highest, lowest....
print(gdp.max())
print(gdp.min())
print(gdp.mean())
print(gdp.sum())
# standardized GDP
(gdp-gdp.mean())/gdp.std()

40034.85063
229.6769525
11289.409271639683
12743.828910617945
711232.7841133


array([-0.70890655, -0.83644045,  0.02449978,  1.09993753,  1.25370438,
        0.6416895 , -0.83970368, -0.65906908,  1.05495905, -0.77242478,
       -0.50895308, -0.68037113, -0.83954024, -0.83362788, -0.32694027,
       -0.67874952, -0.62202214,  0.32084217,  1.53570163, -0.6834911 ,
       -0.37381764, -0.86785003, -0.70989026,  1.27756548,  0.9202445 ,
       -0.78114377, -0.85427339, -0.4113527 , -0.85494663, -0.85561647,
       -0.77491128, -0.43498918, -0.82013522, -0.79116083,  1.28894693,
        0.60012111,  2.21979323, -0.84834706,  0.42332674, -0.86396239,
       -0.4664372 , -0.39243747, -0.73612922, -0.86430354,  0.26342253,
        2.25563616, -0.83312909, -0.62225348,  1.95100371, -0.64617013,
        1.74519145, -0.58572   ,  0.32477772,  1.75307099,  2.18780436,
       -0.67407418,  0.76656923,  1.3326448 ,  2.07171787, -0.13405333,
       -0.44080136, -0.82643987, -0.85858526])

In [14]:
# lesson 06 - Scipy
inverse_array = np.array([[10,6],[2,7]])
inverse_array
np.linalg.inv(inverse_array)


array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [16]:
inverse_array

array([[10,  6],
       [ 2,  7]])

In [1]:
# OR – use numpy package
from scipy import linalg
linalg.inv(inverse_array)


NameError: name 'inverse_array' is not defined

In [20]:
# linear programming example for product A and B with Raw material 1 and Raw material 1  
Beta_coeff = np.array([[1,1],[3,2]])
print(Beta_coeff)
constraints=np.array([5,12])
print(constraints)
from scipy import linalg
linalg.solve(Beta_coeff,constraints)

[[1 1]
 [3 2]]
[ 5 12]


array([2., 3.])

In [28]:
from scipy.stats import norm
norm.rvs(loc=0,scale=1, size=10) 

array([-1.05446309, -1.27487446, -0.31602148, -0.62089724, -1.09081575,
       -0.92203177,  2.8189762 ,  0.86721881,  1.37364421, -1.57453877])

In [29]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [30]:
norm.pdf(5,loc=1,scale=2) 

0.02699548325659403

In [31]:
from scipy.stats import expon
expon.rvs(scale=120,loc=0,size=100)

array([1.38143054e+02, 1.21660189e+02, 1.44167393e+02, 1.96831086e+02,
       2.54382438e+02, 7.78668298e+01, 1.34748852e+02, 1.99348001e+02,
       1.55958442e+02, 1.10578055e+01, 5.87783988e+01, 5.30263002e+00,
       1.75314756e+02, 9.57457642e+01, 2.08975045e+02, 1.95896381e+02,
       4.05470691e+01, 3.11516382e+00, 4.56223070e-01, 3.66466010e+01,
       6.00832823e+01, 1.71565722e+02, 3.49454505e+02, 3.53274783e+01,
       1.20878420e+01, 8.07810100e-01, 1.46108888e+02, 1.20033420e+01,
       1.06791645e+02, 9.66457618e+01, 1.41413820e+01, 9.33115524e+01,
       2.36340118e+01, 3.83867737e+02, 6.58435924e+01, 1.65704094e+01,
       3.96426016e+02, 1.81312826e+02, 3.01239000e+01, 4.48513899e+01,
       9.54539391e+01, 2.32213398e+02, 5.84545282e+01, 1.54358181e+01,
       1.88346673e+02, 1.55642691e+02, 2.32106137e+02, 1.51011774e+02,
       1.05227649e+02, 9.31552991e+00, 1.24257435e+02, 3.24340711e+01,
       1.41972936e+02, 2.69526194e+01, 2.78476821e+01, 1.77202300e+01,
      

In [3]:
#Slide 32 of lesson 6 for activity
true_or_false = np.array([[1,1],[4,9]])
print(true_or_false)
constraints = np.array([30,150])
print(constraints)
from scipy import linalg
linalg.solve(true_or_false,constraints)

[[1 1]
 [4 9]]
[ 30 150]


array([24.,  6.])